const canvas=document.getElementById('simCanvas'),ctx=canvas.getContext('2d');
const state={width:2.4,length:3.2,chassis:'rectangle',paused:false,grid:true,x:0,y:0,r:0,speed:3,heading:0,wheelPhase:0,pos:{x:0,y:0},wheels:[{angle:45,x:-.82,y:-.82},{angle:-45,x:.82,y:-.82},{angle:-45,x:-.82,y:.82},{angle:45,x:.82,y:.82}]};
const $=id=>document.getElementById(id); const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function renderWheelData(){const rows=$('wheelDataRows');if(!rows)return;rows.innerHTML=state.wheels.map((w,i)=>{const angle=w.angle*Math.PI/180;const command=state.speed*(state.x*Math.cos(angle)+state.y*Math.sin(angle))+state.r*(w.x-w.y);const sign=command>0?'+':'';return `<div class="wheel-data-row"><span>W0${i+1}</span><span>${w.angle}°</span><span>${w.x.toFixed(2)}, ${w.y.toFixed(2)}</span><strong class="${command>0.02?'positive':command<-0.02?'negative':''}">${sign}${command.toFixed(2)} m/s</strong></div>`}).join('')}
function renderWheels(){const list=$('wheelList');list.innerHTML='';state.wheels.forEach((w,i)=>{const row=document.createElement('div');row.className='wheel-row';row.innerHTML=`<span class="wheel-index">0${i+1}</span><span class="name">Omni wheel ${i+1}</span><input type="range" min="-180" max="180" value="${w.angle}"><span class="angle">${w.angle}°</span><button class="remove-wheel" title="Remove wheel">×</button>`;const input=row.querySelector('input'), angle=row.querySelector('.angle');input.oninput=()=>{w.angle=+input.value;angle.textContent=`${w.angle}°`;renderWheelData();draw()};row.querySelector('.remove-wheel').onclick=()=>{if(state.wheels.length>3){state.wheels.splice(i,1);renderWheels();draw()}};list.appendChild(row)});$('wheelCount').textContent=state.wheels.length;renderWheelData()}
function sync(id,key,out,fmt=v=>v.toFixed(2)){const el=$(id);el.oninput=()=>{state[key]=+el.value;$(out).textContent=fmt(state[key]);renderWheelData();draw()}}
sync('widthRange','width','widthValue');sync('lengthRange','length','lengthValue');sync('xRange','x','xValue');sync('yRange','y','yValue');sync('rotationRange','r','rotationValue');sync('speedRange','speed','speedValue',v=>`${v.toFixed(1)} m/s`);
function roundedRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}
function draw(){const dpr=devicePixelRatio||1,rect=canvas.getBoundingClientRect();if(canvas.width!==rect.width*dpr){canvas.width=rect.width*dpr;canvas.height=620*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=620,s=Math.min(W/9.2,H/7.1),cx=W/2+state.pos.x*s,cy=H/2+state.pos.y*s;ctx.clearRect(0,0,W,H);ctx.fillStyle='#fbfcfb';ctx.fillRect(0,0,W,H);if(state.grid){ctx.strokeStyle='#edf0ee';ctx.lineWidth=1;for(let x=0;x<W;x+=s/2){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=s/2){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
 const scale=s*.88,ang=state.heading;ctx.save();ctx.translate(cx,cy);ctx.rotate(ang);const cw=state.width*scale/2,cl=state.length*scale/2;ctx.shadowColor='rgba(30,35,40,.12)';ctx.shadowBlur=28;ctx.shadowOffsetY=12;ctx.fillStyle='#262b32';ctx.beginPath();if(state.chassis==='triangle'){ctx.moveTo(0,-cl-18);ctx.lineTo(cw+24,cl+10);ctx.lineTo(-cw-24,cl+10);ctx.closePath()}else ctx.roundRect(-cw,-cl,cw*2,cl*2,18);ctx.fill();ctx.shadowColor='transparent';ctx.fillStyle='#30363e';if(state.chassis==='rectangle')ctx.fillRect(-cw+18,-cl+18,cw*2-36,6);ctx.fillStyle='#c8f22e';ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='#262b32';ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();
 state.wheels.forEach((w,i)=>{let wx=state.chassis==='triangle'?(i===0?0:(i===1?-.9:.9))*cw*.92:(w.x)*cw*1.2;let wy=state.chassis==='triangle'?(i===0?-1.02:1.02)*cl*.8:w.y*cl*1.2;ctx.save();ctx.translate(wx,wy);ctx.rotate((w.angle*Math.PI)/180);ctx.fillStyle='#161a1f';ctx.beginPath();ctx.roundRect(-11,-28,22,56,7);ctx.fill();ctx.save();ctx.clip();ctx.translate(0,state.wheelPhase%14);ctx.fillStyle='#c8f22e';for(let mark=-70;mark<70;mark+=18)ctx.fillRect(-8,mark,16,6);ctx.restore();ctx.fillStyle='#69727c';ctx.fillRect(-8,-18,16,4);ctx.fillRect(-8,14,16,4);ctx.restore()});ctx.restore();
 const vx=state.x,vy=state.y;ctx.strokeStyle='#ff704e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+vx*s*1.8,cy-vy*s*1.8);ctx.stroke();if(Math.hypot(vx,vy)>.03){ctx.fillStyle='#ff704e';ctx.beginPath();ctx.arc(cx+vx*s*1.8,cy-vy*s*1.8,5,0,Math.PI*2);ctx.fill()}$('velocityReadout').textContent=`${(Math.hypot(vx,vy)*state.speed).toFixed(2)} m/s`;$('headingReadout').textContent=`${Math.round(state.heading*180/Math.PI)}°`}
let controllerIndex=null,controllerName='waiting';
function setDrive(x,y,r){state.x=clamp(x,-1,1);state.y=clamp(y,-1,1);state.r=clamp(r,-1,1);$('xRange').value=state.x;$('yRange').value=state.y;$('rotationRange').value=state.r;$('xValue').textContent=state.x.toFixed(2);$('yValue').textContent=state.y.toFixed(2);$('rotationValue').textContent=state.r.toFixed(2)}
function scanControllers(){const pads=navigator.getGamepads?navigator.getGamepads():[];let found=-1;for(let i=0;i<pads.length;i++)if(pads[i]){found=i;break}if(found!==controllerIndex){controllerIndex=found;controllerName=found>=0?(pads[found].id||'Controller'):'waiting';$('controllerBtn').textContent=found>=0?'⌁ Controller: connected':'⌁ Controller: waiting';$('controllerBtn').classList.toggle('connected',found>=0)}}
function readController(){scanControllers();if(controllerIndex===null||controllerIndex<0)return;const pad=navigator.getGamepads()[controllerIndex];if(!pad)return;const dead=v=>Math.abs(v)<.12?0:v;setDrive(dead(pad.axes[0]||0),-dead(pad.axes[1]||0),dead(pad.axes[2]||pad.axes[3]||0))}
function animate(){if(!state.paused){readController();const drive=Math.hypot(state.x,state.y);state.wheelPhase+=drive*state.speed*.8+Math.abs(state.r)*state.speed*.35;state.pos.x=clamp(state.pos.x+state.x*.006*state.speed,-2.1,2.1);state.pos.y=clamp(state.pos.y-state.y*.006*state.speed,-1.35,1.35);state.heading+=state.r*.003*state.speed}draw();requestAnimationFrame(animate)}
window.addEventListener('gamepadconnected',e=>{controllerIndex=e.gamepad.index;controllerName=e.gamepad.id||'Controller';$('controllerBtn').textContent='⌁ Controller: connected';$('controllerBtn').classList.add('connected')});window.addEventListener('gamepaddisconnected',e=>{if(e.gamepad.index===controllerIndex){controllerIndex=null;setDrive(0,0,0);$('controllerBtn').textContent='⌁ Controller: waiting';$('controllerBtn').classList.remove('connected')}});$('controllerBtn').onclick=()=>{scanControllers();if(controllerIndex===null||controllerIndex<0){$('controllerBtn').textContent='⌁ Press a controller button…';canvas.focus?.()}else{$('controllerBtn').textContent=`⌁ ${controllerName.slice(0,22)}`}};
$('addWheelBtn').onclick=()=>{const n=state.wheels.length;state.wheels.push({angle:n%2? -45:45,x:n%2?-.82:.82,y:n<4?.82:0});renderWheels();draw()};$('resetBtn').onclick=()=>{state.pos={x:0,y:0};['x','y','r'].forEach(k=>{state[k]=0});['xRange','yRange','rotationRange'].forEach(id=>$(id).value=0);['xValue','yValue','rotationValue'].forEach(id=>$(id).textContent='0.00');draw()};$('gridBtn').onclick=()=>{state.grid=!state.grid;$('gridBtn').classList.toggle('active',state.grid)};$('pauseBtn').onclick=()=>{state.paused=!state.paused;$('pauseBtn').textContent=state.paused?'▶ Play':'Ⅱ Pause'};document.querySelectorAll('[data-chassis]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-chassis]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.chassis=b.dataset.chassis;draw()});window.onkeydown=e=>{const k=e.key.toLowerCase();if('wasd'.includes(k)){if(k==='w')state.y=1;if(k==='s')state.y=-1;if(k==='a')state.x=-1;if(k==='d')state.x=1;['x','y'].forEach(k=>{$(k+'Range').value=state[k];$(k+'Value').textContent=state[k].toFixed(2)})}};window.onkeyup=e=>{if('wasd'.includes(e.key.toLowerCase())){$('xRange').value=$('yRange').value=0;state.x=state.y=0;$('xValue').textContent=$('yValue').textContent='0.00'}};renderWheels();animate();
